version: '3.7'

services:
  currency-exchange:
    image: imrohan/microservice-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 400m
    ports:
      - "8000:8000"
    networks:
     - currency-network

    depends_on:
      - naming-server

    environment:
       EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/naming-server/eureka
       SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  naming-server:
    image: imrohan/naming-server:0.0.1-SNAPSHOT
    mem_limit: 400m
    ports:
    - "8761:8761"
    networks:
      - currency-network

  currency-conversion:
    image: imrohan/microservice-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 400m
    ports:
      - "8100:8100"
    networks:
     - currency-network

    depends_on:
      - naming-server

    environment:
       EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/naming-server/eureka
       SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  api-gateway:
     image: imrohan/api-gateway:0.0.1-SNAPSHOT
     mem_limit: 400m
     ports:
      - "8765:8765"
     networks:
     - currency-network

     depends_on:
      - naming-server

     environment:
       EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/naming-server/eureka
       SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 400m
    ports:
    - "9411:9411"
    networks:
      - currency-network

networks:
  currency-network:
